name: caldav
description: A CalDAV API for Dart

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  xml: ^3.5.0
  http: ^0.12.0+4
  http_auth: ^0.2.9
  quiver: ^2.1.2
  meta: ^1.1.8

dev_dependencies:
  test: ^1.12.0
  mockito: ^4.1.1
  effective_dart: ^1.2.0